import Head from "next/head";
import { AiFillLinkedin, AiFillGithub, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import design from "../public/design.png";
import code from "../public/code.png";
import thumb from "../public/thumb.png";
import hulu from "../public/hulucloneSS.png";
import petLyfe from "../public/petlyfe.png";
import pokedex from "../public/pokedex.png";
import morty from "../public/morty.png";
import breddit from "../public/breddit.png";
import sandyai from "../public/SandyAi.jpg";
import { useState } from "react";
import Navbar from "./components/Navbar.jsx";
import About from "./components/About.jsx"
import Skills from "./components/Skills.jsx"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const handleClickGit = () => {
    window.open("https://github.com/limbocaba", "_blank");
  };

  const handleClickLinked = () => {
    window.open("https://www.linkedin.com/in/jorielcaba2002/", "_blank");
  };

  const handleClickHulu = () => {
    window.open("https://github.com/limbocaba/Hulu-Clone", "_blank");
  };

  const handleClickPoke = () => {
    window.open("https://github.com/limbocaba/Pokedex-API", "_blank");
  };

  const handleClickMorty = () => {
    window.open("https://github.com/limbocaba/Frontend-Game", "_blank");
  };

  const handleClickPet = () => {
    window.open(
      "https://github.com/Brandon-Alvarez-03/pet-style-mern",
      "_blank"
    );
  };

  const handleClickResume = () => {
    window.open("https://drive.google.com/file/d/1unJpBlTzcZ7ZHZ5x2s1xoWcDM3qY2Yeo/view?usp=sharing", "_blank")
  }

  const handleClickBred = () => {
    window.open("https://breddit.netlify.app/","_blank")
  }

  const handleClickWrong = () => {

  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sandy Caba Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white dark:bg-gray-900">
        <section className=" min-h-screen">
          <Navbar />
          




            {/* <h1 className=" font-burtons text-xl dark:text-white">
              <Link href='/'>
                About Me
              </Link>
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 hover:text-black cursor-pointer dark:bg-gradient-to-r dark:from-purple-500 dark:to-red-500 dark:text-black dark:hover:text-white"
                  onClick={handleClickResume}
                >
                  Resume
                </a>
              </li>
            </ul> */}
          <div className="text-center p-[100px]">
            <h2 className="text-5xl py-2 text-black font-medium md:text-6xl dark:text-purple-400">
              Sandy J Caba
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Full Stack Developer
            </h3>
            <p className="text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white font-burtons">
             Eager and driven software developer bursting into the tech indutsry ready to learn as much as I can!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin
              className=" cursor-pointer hover:text-blue-700"
              onClick={handleClickLinked}
            />
            <AiFillGithub
              className=" cursor-pointer hover:text-black dark:hover:text-white"
              onClick={handleClickGit}
            />
            <AiFillMail
              className=" cursor-pointer hover:text-black dark:hover:text-white"
            />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={sandyai} alt="" layout="fill" objectFit="cover" />
          </div>
        </section>
        <section className=" p-20">
          <div>
            <h3 className="text-3xl py-1 dark:text-purple-500">
            </h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white">
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white hover:scale-105 ease-in duration-200 hover:shadow-blue-100">
              {/* <Image src={code} alt="" width={100} height={100} /> */}
              <h3 className="text-large font-medium pt-8 pb-2">
                How old is Sandy?
              </h3>
              <p className="py-2">
                Care for a quick game while you are here?
              </p>
              <p className="  py-1 hover:text-green-500 cursor-default text-xl">A. 20</p>
              <p className="  py-1 hover:text-red-600 cursor-default text-xl">B. 24</p>
              <p className="  py-1 hover:text-red-600 cursor-default text-xl">C. 32</p>
              <p className=" py-1 hover:text-red-600 cursor-default text-xl">D. 67</p>
              <p></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white hover:scale-105 ease-in duration-200 hover:shadow-blue-100">
              {/* <Image src={design} alt="" width={100} height={100} /> */}
              <h3 className="text-large font-medium pt-8 pb-2">
               Which does Sandy prefer more?
              </h3>
              <p className="py-2">
                Although they are both very useful, I do like one more than the other!
              </p>
              <h4 className="py-4 text-teal-600"></h4>
              <p className=" hover:text-green-400 py-1 cursor-default text-xl">A. Front-End</p>
              <p className=" hover:text-red-500 py-1 cursor-default text-xl">B. Back-End</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white hover:scale-105 ease-in duration-200 hover:shadow-blue-100">
              {/* <Image src={thumb} alt="" width={100} height={100} /> */}
              <h3 className="text-large font-medium pt-8 pb-2">
                Should you hire Sandy to your company?
              </h3>
              <p className="py-2">
               Theres only one right answer!
              </p>
              <p className=" hover:text-green-400 py-1 cursor-default text-xl">A. Yes</p>
              <p className=" hover:text-green-400 py-1 cursor-default text-xl font-bold">B. Yes but in bold</p>
            </div>
          </div>
        </section>
        <section>
          <Skills />
          <About />
          <div>
            <div className="flex justify-center">
              <h3 className="text-3xl py-1 justify-center underline font-semibold dark:text-purple-400">
                Projects
              </h3>
            </div>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"></p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap p-20">
            <div className="basis-1/3 flex-1">
              <Image
                src={hulu}
                className="rounded-lg object-cover cursor-pointer transition hover:-translate-y-1 hover:scale-110 hover:brightness-50"
                alt=""
                onClick={handleClickHulu}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={pokedex}
                className="rounded-lg object-cover cursor-pointer transition hover:-translate-y-1 hover:scale-110 hover:brightness-50"
                alt=""
                onClick={handleClickPoke}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={petLyfe}
                className="rounded-lg object-cover cursor-pointer transition hover:-translate-y-1 hover:scale-110 hover:brightness-50"
                alt=""
                onClick={handleClickPet}
              />
            </div>
            <div className="basis-1/3 flex-1">
               <Image
                src={breddit}
                alt=""
                className="rounded-lg object-cover cursor-pointer transition hover:-translate-y-1 hover:scale-110 hover:brightness-50"
                onClick={handleClickBred}
              /> 
            </div>
          </div>
        </section>
      </main>
      {/* <About /> */}
    </div>
  );
}